### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Kanielyochanan**

### CODE REVIEW

**Comment by Kanielyochanan** [comment]
I don't like how GitHub automatically selected a pull request.

**Comment by kanielyaniel** [comment]
In the modified code, Monika is not trying to find anyone, but just checking IDs, so there's no real reason to merge this.

**Comment by tangalbert919** [comment]
If I were to use $!delete on a player that isn't in a server, it would give an exception message and exception messages are not fun to look at.

**Comment by kanielyaniel** [comment]
Ah, I see what you're doing now. I'll merge this but first change it to be more in character

**Pull request merged**
