### PR TITLE
#8: Hotfixes and Konachan

### PR DESCRIPTION
**Pull request by tangalbert919**
This is mostly quality control, bug fixes, and [Konachan](http://konachan.com). That's not a reference to Kanielyochanan.

### CODE REVIEW

**Comment by KnifuWaifu** [comment]
#Kayla4SSR

**Comment by KnifuWaifu** [comment]
#Kayla4SSR

**Comment by tangalbert919** [comment]
On June 3, tune in live to watching me make Monika connect to [yande.re](https://yandere.re). You're going to hate it.

**Comment by tangalbert919** [comment]
***AND LIVE FROM NEW YORK, IT'S SATURDAY NIGHT!!!***

**Comment by Sanae6** [comment]
dead this isn't going to even get pulled in

it's too old now rip in peace

**Comment by KnifuWaifu** [comment]
rip

**Comment by KnifuWaifu** [comment]
can we SMASH that like button?!?!!?!!?!!?!?11!?!?!?!1/!!?!

**Comment by KnifuWaifu** [comment]
CAN WE HIT ONE BILLION LIKES?!!?!?!?!?!??!111!!?!?!??!?!?1/1'1/11][l[c
cdiewp apwirEagwiropF

f

**Comment by Sanae6** [comment]
i am prepared to end you

**Pull request closed without merging**
