### PR TITLE
A summary of some implementations

### PR DESCRIPTION
**Pull request by gpago**
My additions, fixes, and changes to Monika's code at a stable point.

The entire repo shouldn't be merged. but there are part of code that are just improvements, and may therefore be welcome..

Notably:
- Lavalink (single line) fix
- Command check flag for NSWF
- Addition of custom messages for command checks

### CODE REVIEW

**Comment by Sanae6** [comment]
kaniel and i will take a look at it, but i'm wondering if it has been tested yet seeing as you said in the support chat that you have a self-hosted version

**Comment by gpago** [comment]
Yes, it does work for me, however I have a docker installation on which I'm hosting it. Lavalink for docker seems to not want to play, but that's a separate thing. (could be firewall related)

**Comment by kanielyaniel** [comment]
Hi, so I've reviewed your pull request.

Most of these commits come before Monika was back alive, so some of these changes would revert our changes that we've done since Monika was reborn.

Also, Monika's source code is not made available to self-host her, but to use some of the code as a reference. It would actually be really hard to get all the API keys needed to use Monika. Anyways, this eliminates some changes, such as the Lavalink port configuration. (config.json is just there for us so we can just do a simple git pull whenever adding changes.)

Anyways, I hope this helps you understand why I won't merge this pull request.
(I'm actually really sorry for making all that effort go to waste, I know what it feels like)

**Comment by gpago** [comment]
No worries.
I had fun (and frustration) working and learning how the code worked. 😃 

I changed the config heavily, both because I was hosting everything in Docker, and because I was making a configurator script to help anyone fill in values from the CLI. (And cause I love modular designs)

The part about self-hosting her, was just a concept I had about being able to deploy node-like versions that would not need an API key and would connect to a main version to offload some work (kinda like sharding, but not really).

Regardless, the configurator was never completed, and the node-like deployment is just a concept, so no real work (apart from the command checks) was lost I guess. 😔 

So keep up the great work! 😄

**Pull request closed without merging**
